//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodPlaysEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItem
    {
        public int ListItemID { get; set; }
        public string UserID { get; set; }
        public int ListType { get; set; }
        public int GameID { get; set; }
    
        public virtual ListType ListType1 { get; set; }
        public virtual User User { get; set; }
    }
}
